name: CI Run Upload To Big Query

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GCloud account setup
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_GH_ACTIONS_SA_KEY }}
          export_default_credentials: true

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Installing gcp libraries
        run: |
          pip install google-cloud-bigquery
          pip install google-cloud-storage

      - name: Uploading csv files to workload layer
        run: python src/uploadtoworkloadlayer.py

        #Run dataproc

      - name: Uploading parquet files to BigQuery
        run: python src/uploadingtobigquery.py
